---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cluster-proportional-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proportional-autoscaler
subjects:
- kind: ServiceAccount
  name: cluster-proportional-autoscaler
  namespace: kube-system

