---

- name: shared/mount | Test if PKI mount exists
  uri:
    url: "{{ vault_leader_url }}/v1/sys/mounts/{{ mount_name }}/tune"
    headers: "{{ vault_headers }}"
  environment:
    http_proxy: "{{ uri_proxy_http | default('') }}"
    https_proxy: "{{ uri_proxy_https | default('') }}"
  ignore_errors: true
  register: vault_pki_mount_check

- name: shared/mount | Mount PKI mount if needed
  uri:
    url: "{{ vault_leader_url }}/v1/sys/mounts/{{ mount_name }}"
    headers: "{{ vault_headers }}"
    method: POST
    body_format: json
    body: "{{ mount_options|d() }}"
    status_code: 204
  environment:
    http_proxy: "{{ uri_proxy_http | default('') }}"
    https_proxy: "{{ uri_proxy_https | default('') }}"
  when: vault_pki_mount_check|failed
